### ISSUE TITLE
The bundle name is incorrect when using symfony flex

### ISSUE THREAD

**Issue by chrisyue** [EasyCorp/easy-deploy-bundle#29]
symfony/flex version 1.0.14

after installing this bundle by 

```
$ composer require --dev easycorp/easy-deploy-bundle
```

as https://github.com/EasyCorp/easy-deploy-bundle/blob/master/doc/installation.md mentioned,

the code generated in `config/bundles.php` is 

```
    'EasyCorp\Bundle\EasyDeployBundle\EasyCorpEasyDeployBundle' => ['dev' => true, 'test' => true],
```

which the class name is incorrect.

**Comment by anacona16** [comment]
@chrisyue this issue is already been discussed [here](https://github.com/symfony/flex/issues/59)
