### ISSUE TITLE
Composer is in a different directory from /usr/local/bin

### ISSUE THREAD

**Issue by xeon826** [EasyCorp/easy-deploy-bundle#75]
Is there an option to set in deploy.php to tell easy-deploy where composer is located? For clarification, I installed composer [this](https://www.namecheap.com/support/knowledgebase/article.aspx/9977/29/how-to-install-composer-on-shared-servers) way, so it's in /opt/cpanel/composer/bin/composer, it's a shared server.

**Comment by genr8r** [comment]
Yes. You can set the path to composer using...
->remoteComposerBinaryPath(string $path = '/path/to/your/bin/composer')

mine didn't need it set as a $path variable. So, I just have...
->remoteComposerBinaryPath('/path/to/your/bin/composer')

More options for your deploy.php can be found at https://github.com/EasyCorp/easy-deploy-bundle/blob/master/doc/default-deployer.md#configuration
