### ISSUE TITLE
ABANDONED?

### ISSUE THREAD

**Issue by LauLaman** [EasyCorp/easy-deploy-bundle#97]
I see that no commits have been pushed to master since  Apr 21, 2018
Also quite some PRs are open which have not received any feedback
 
so... Is this project abandoned?

**Comment by AntoineFacq** [comment]
https://easycorp.io/EasyDeploy here is the (formal) answer!

**Comment by gustawdaniel** [comment]
But last closed pull request

#58 by javiereguiluz was merged on 21 Apr 2018

and there is 15 open pull requests waiting for consideration.

Who can decide if these pull request should be rejected or accepted?

**Comment by COil** [comment]
A new tag has been released. Can you close this please? :)
